export const STORE_EMAIL_PASS = "STORE_EMAIL_PASS";
export const STORE_STUDENT_INFO = "STORE_STUDENT_INFO";
export const STORE_PRINCIPAL_INFO = "STORE_PRINCIPAL_INFO";
export const STORE_SCHOOL_INFO = "STORE_SCHOOL_INFO";
export const STORE_TEACHER_INFO = "STORE_TEACHER_INFO";
// export const TOGGLE_CHAT = "TOGGLE_CHAT";
